name: Terraform CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Clone Code
        uses: actions/checkout@v4
        with:
          repository: harish4csl/Tearrform-009PM-practice
          ref: main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        working-directory: Day2-sample-base-code
        run: terraform init

      - name: Terraform Plan
        working-directory: Day2-sample-base-code
        run: terraform plan

      - name: Terraform destroy
        working-directory: Day2-sample-base-code
        run: terraform destroy -auto -approve
